### PR TITLE
Add VOEvet generation to rfpipe.candidates.py

### PR DESCRIPTION
**Pull request by astrolobo**
VOEvent generation added to rfpipe.candidates.py.  Using information CandCollection.  Creates VOEvent .xml file for each source in CandCollection.

### CODE REVIEW

**Comment by caseyjlaw** [comment]
I'm looking things over now. It seems that your fork was pretty old, so there are a lot of merge conflicts. That's because I made a bunch of edits since the point you forked off and git does not know how to add yours in so far back.
Is your change largely contained to one function? If so, then I'd suggest we get your fork up to date before you make a new commit. Updating your fork would be done with the pull request option, as you just did, but the 'head' would be your fork, rather that mine.
Willing to give that a try?

**Comment by caseyjlaw** [comment]
Thanks!
Not sure why, but it looks like this still hasn't merged in changes to the development branch in the last week or two. Could you try another merge from `realfastvla/development` and then commit your change?

**Comment by caseyjlaw** [comment]
It seems to still have the same issue. For example, if you look at this PR under "Files Changed", it has many files changed (e.g., "calibration.py", "search.py"). Your edits should only touch on one, I believe.

Can you try merging the latest from my development branch and then do `git log`? It should show a recent commit by me with a comment "not replacing zeros in spec_std...". Then you need to edit the files in that commit and make changes to add your work.
It may be that when you merged, you undid some my edits. We need you to get to the latest commits and *then* edit your files. (Sorry I don't know how to explain this better; I bet others know how to do it better.)

**Comment by astrolobo** [comment]
I have updated all of my scripts "by hand" (copy from the development branch, pasted into my local versions, pushed to GitHub).  Hopefully, this means the only differences between the two are the VOEvent generation that I added.

**Comment by caseyjlaw** [comment]
I did a bit more by hand and merged it.
I would like to remove the call to the function for now, since that would mean we'd get lots of xml files written in the realtime environment. Some more thinking needed on how to integrate this, probably with the portal.
Thanks for your contribution and your first github PR!

**Pull request merged**
